/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

const keywords = [
  'workflow', 'input', 'signal', 'outcome', 'type', 'schema', 'worker',
  'action', 'child', 'step', 'after', 'fork', 'join', 'loop', 'counting',
  'until', 'max', 'sequential', 'spawn', 'wait', 'sleep', 'timeout',
  'retry', 'every', 'backoff', 'node', 'on', 'failure', 'when',
  'otherwise', 'route', 'success', 'filter', 'map', 'sort', 'count', 'is',
  'empty', 'present', 'absent', 'not', 'and', 'or', 'in',
];

module.exports = grammar({
  name: 'awl',

  extras: $ => [/[ \t\r]/],

  word: $ => $.identifier,

  rules: {
    source_file: $ => repeat(choice(
      $.workflow_declaration,
      $.input_declaration,
      $.signal_declaration,
      $.outcome_declaration,
      $.type_declaration,
      $.worker_declaration,
      $.action_declaration,
      $.child_declaration,
      $.step_declaration,
      $.fork_statement,
      $.join_statement,
      $.loop_statement,
      $.wait_statement,
      $.sleep_statement,
      $.failure_handler,
      $.route_statement,
      $.spawn_statement,
      $.configuration,
      $.doc_comment,
      $.comment,
      $.string,
      $.duration,
      $.float,
      $.integer,
      $.boolean,
      $.builtin_type,
      $.type_identifier,
      $.identifier,
      $.pipe_operator,
      $.bind_operator,
      $.comparison_operator,
      $.optional_operator,
      $.punctuation,
      $.keyword,
      $.newline,
    )),

    workflow_declaration: $ => prec(1, seq(alias('workflow', $.keyword), field('name', $.identifier))),
    input_declaration: $ => prec(1, seq(alias('input', $.keyword), field('name', $.identifier))),
    signal_declaration: $ => prec(1, seq(alias('signal', $.keyword), field('name', $.identifier))),
    outcome_declaration: $ => prec(1, seq(alias('outcome', $.keyword), field('name', $.identifier))),
    type_declaration: $ => prec(1, seq(alias('type', $.keyword), field('name', $.type_identifier))),
    worker_declaration: $ => prec(1, seq(alias('worker', $.keyword), field('name', $.identifier))),
    action_declaration: $ => prec(1, seq(alias('action', $.keyword), field('name', $.identifier))),
    child_declaration: $ => prec(1, seq(alias('child', $.keyword), field('name', $.identifier))),
    step_declaration: $ => prec(1, seq(alias('step', $.keyword), field('name', $.identifier))),
    fork_statement: $ => prec(1, alias('fork', $.keyword)),
    join_statement: $ => prec(1, alias('join', $.keyword)),
    loop_statement: $ => prec(1, alias('loop', $.keyword)),
    wait_statement: $ => prec(1, alias('wait', $.keyword)),
    sleep_statement: $ => prec(1, alias('sleep', $.keyword)),
    failure_handler: $ => prec(1, seq(alias('on', $.keyword), alias('failure', $.keyword))),
    route_statement: $ => prec(1, alias('route', $.keyword)),
    spawn_statement: $ => prec(1, alias('spawn', $.keyword)),
    configuration: $ => prec(1, choice(
      alias('node', $.keyword), alias('timeout', $.keyword), alias('retry', $.keyword),
    )),

    doc_comment: _ => token(choice(seq('//!', /[^\n]*/), seq('///', /[^\n]*/))),
    comment: _ => token(seq('//', /[^!\/\n][^\n]*|[^\n]?/)),
    string: _ => token(/"(?:[^"\\\n]|\\.)*"/),
    duration: _ => token(/[0-9]+(?:s|m|h|d)/),
    float: _ => token(/-?(?:[0-9]+\.[0-9]+(?:[eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+)/),
    integer: _ => token(/-?[0-9]+/),
    boolean: _ => choice('true', 'false'),
    builtin_type: _ => choice('Bool', 'Int', 'Float', 'String', 'Nil', 'Dir'),
    type_identifier: _ => token(/[A-Z][A-Za-z0-9_]*/),
    identifier: _ => token(/[a-z_][a-zA-Z0-9_]*/),

    pipe_operator: _ => '|>',
    bind_operator: _ => '->',
    comparison_operator: _ => choice('==', '!=', '<=', '>=', '<', '>', '+', '..'),
    optional_operator: _ => '?',
    punctuation: _ => choice('(', ')', '[', ']', '{', '}', ':', ',', '.', '=', '|'),
    keyword: _ => choice(...keywords),
    newline: _ => /\n/,
  },
});
